// src/utils/tax/countryMeta.ts
export interface CountryMeta {
  code: string;
  name: string;
  symbol: string;
  emoji: string;
}

export const countries: CountryMeta[] = [
  { code: 'US', name: 'United States', symbol: '$', emoji: '🇺🇸' },
  { code: 'IN', name: 'India', symbol: '₹', emoji: '🇮🇳' },
  { code: 'UK', name: 'United Kingdom', symbol: '£', emoji: '🇬🇧' },
  { code: 'CA', name: 'Canada', symbol: 'C$', emoji: '🇨🇦' },
  { code: 'AU', name: 'Australia', symbol: 'A$', emoji: '🇦🇺' },
  { code: 'SG', name: 'Singapore', symbol: 'S$', emoji: '🇸🇬' },
  { code: 'NZ', name: 'New Zealand', symbol: 'NZ$', emoji: '🇳🇿' },
  { code: 'DE', name: 'Germany', symbol: '€', emoji: '🇩🇪' },
  { code: 'FR', name: 'France', symbol: '€', emoji: '🇫🇷' },
  { code: 'IT', name: 'Italy', symbol: '€', emoji: '🇮🇹' },
  { code: 'ES', name: 'Spain', symbol: '€', emoji: '🇪🇸' },
  { code: 'BR', name: 'Brazil', symbol: 'R$', emoji: '🇧🇷' },
  { code: 'MX', name: 'Mexico', symbol: 'MX$', emoji: '🇲🇽' },
  { code: 'JP', name: 'Japan', symbol: '¥', emoji: '🇯🇵' },
  { code: 'KR', name: 'South Korea', symbol: '₩', emoji: '🇰🇷' },
  { code: 'CN', name: 'China', symbol: '¥', emoji: '🇨🇳' },
  { code: 'ZA', name: 'South Africa', symbol: 'R', emoji: '🇿🇦' },
  { code: 'AE', name: 'United Arab Emirates', symbol: 'د.إ', emoji: '🇦🇪' },
  { code: 'SA', name: 'Saudi Arabia', symbol: '﷼', emoji: '🇸🇦' },
  { code: 'RU', name: 'Russia', symbol: '₽', emoji: '🇷🇺' },
  { code: 'SE', name: 'Sweden', symbol: 'kr', emoji: '🇸🇪' },
  { code: 'NO', name: 'Norway', symbol: 'kr', emoji: '🇳🇴' },
  { code: 'FI', name: 'Finland', symbol: '€', emoji: '🇫🇮' },
  { code: 'CH', name: 'Switzerland', symbol: 'CHF', emoji: '🇨🇭' },
  { code: 'NL', name: 'Netherlands', symbol: '€', emoji: '🇳🇱' },
  { code: 'BE', name: 'Belgium', symbol: '€', emoji: '🇧🇪' },
  { code: 'IE', name: 'Ireland', symbol: '€', emoji: '🇮🇪' },
  { code: 'DK', name: 'Denmark', symbol: 'kr', emoji: '🇩🇰' },
  { code: 'AT', name: 'Austria', symbol: '€', emoji: '🇦🇹' },
  { code: 'PL', name: 'Poland', symbol: 'zł', emoji: '🇵🇱' },
  { code: 'CZ', name: 'Czech Republic', symbol: 'Kč', emoji: '🇨🇿' },
  { code: 'HU', name: 'Hungary', symbol: 'Ft', emoji: '🇭🇺' },
  { code: 'GR', name: 'Greece', symbol: '€', emoji: '🇬🇷' },
  { code: 'PT', name: 'Portugal', symbol: '€', emoji: '🇵🇹' },
  { code: 'TH', name: 'Thailand', symbol: '฿', emoji: '🇹🇭' },
  { code: 'MY', name: 'Malaysia', symbol: 'RM', emoji: '🇲🇾' },
  { code: 'ID', name: 'Indonesia', symbol: 'Rp', emoji: '🇮🇩' },
  { code: 'PH', name: 'Philippines', symbol: '₱', emoji: '🇵🇭' },
  { code: 'VN', name: 'Vietnam', symbol: '₫', emoji: '🇻🇳' },
  { code: 'EG', name: 'Egypt', symbol: '£', emoji: '🇪🇬' },
  { code: 'TR', name: 'Turkey', symbol: '₺', emoji: '🇹🇷' },
  { code: 'IL', name: 'Israel', symbol: '₪', emoji: '🇮🇱' },
  { code: 'NG', name: 'Nigeria', symbol: '₦', emoji: '🇳🇬' },
  { code: 'KE', name: 'Kenya', symbol: 'KSh', emoji: '🇰🇪' },
  { code: 'AR', name: 'Argentina', symbol: 'ARS$', emoji: '🇦🇷' },
  { code: 'CL', name: 'Chile', symbol: 'CLP$', emoji: '🇨🇱' },
  { code: 'CO', name: 'Colombia', symbol: 'COL$', emoji: '🇨🇴' },
  { code: 'BD', name: 'Bangladesh', symbol: '৳', emoji: '🇧🇩' },
  { code: 'PK', name: 'Pakistan', symbol: '₨', emoji: '🇵🇰' },
  { code: 'LK', name: 'Sri Lanka', symbol: 'Rs', emoji: '🇱🇰' },
];
